import { shellQuote } from "../core/shell-quote";

/**
 * One owner per process.
 *
 * Shopify CLI starts every `shopify.web.toml` it finds, and an empty
 * `web_directories` means "find them all", so it ran a second API and a
 * second Vite beside buncargo's. Instead the app toml points at one generated
 * web whose fixed `port` is buncargo's frontend, and whose `dev` command only
 * waits for that frontend and holds: the CLI keeps its tunnel and proxy, and
 * buncargo keeps every process.
 */

export const SHOPIFY_WEB_DIR = ".buncargo/shopify/web";

export function renderShopifyWebToml(input: {
	frontend: string;
	port: number | undefined;
	/** The buncargo that started the run: `[program, script?]`. */
	buncargo: readonly string[];
}): string {
	const wait = [
		...input.buncargo,
		"wait",
		`--app=${input.frontend}`,
		"--hold",
		"--timeout=0",
	]
		.map(shellQuote)
		.join(" ");
	return [
		"# Generated by buncargo on every run; do not edit.",
		`# Shopify CLI proxies to ${input.frontend} on its buncargo port and starts nothing itself.`,
		`name = "buncargo-frontend"`,
		`roles = ["frontend"]`,
		...(input.port === undefined ? [] : [`port = ${input.port}`]),
		"",
		"[commands]",
		`dev = ${JSON.stringify(wait)}`,
		"",
	].join("\n");
}

const WEB_DIRECTORIES = /^web_directories\s*=\s*\[[^\]]*\][^\n]*$/m;

/**
 * Point an app toml's `web_directories` at the generated web, keeping every
 * other line (and its comments) as written. A top-level key has to come
 * before the first table, so a missing one is inserted there.
 */
export function patchWebDirectories(toml: string): string {
	const line = `web_directories = [${JSON.stringify(SHOPIFY_WEB_DIR)}]`;
	if (WEB_DIRECTORIES.test(toml)) return toml.replace(WEB_DIRECTORIES, line);

	const firstTable = toml.search(/^\[/m);
	if (firstTable < 0) return `${toml.replace(/\n*$/, "\n")}${line}\n`;
	return `${toml.slice(0, firstTable)}${line}\n\n${toml.slice(firstTable)}`;
}
